[project]
name = "filetags"
requires-python = ">=3.9"

[build-system]
requires = ["setuptools>=75.6.0"]
build-backend = "setuptools.build_meta"

[project]
dependencies = [
    "clint",
    "colorama",
    "pyreadline3"
]